### ISSUE TITLE
iPhone Control Center switching dark mode does not trig the plugin

### ISSUE THREAD

**Issue by arnotixe** [aparajita/capacitor-dark-mode#6]
iOS only: Control Center / "Widget" switching dark mode does not trig the plugin, and app does not switch mode until killed.

Workarounds:
1) Either switch from Settings → Display or
2) Switch in Control center, kill app and restart. It starts in correct dark/light mode.

Attached video shows working live mode switch when switching from Settings→Display, but not when switching with the Control Center widget/switch.

I first suspected a fake/different darkmode switch from Control Center, but when killing+restarting the app it actually does pick up real dark mode.

https://user-images.githubusercontent.com/500938/212443394-136d7f8f-d62b-4511-ad0c-d719e7c5c53a.mp4

**Comment by aparajita** [comment]
It definitely does get triggered when Control Center changes mode, which you can verify by registering an appearance listener. The problem is Ionic does not properly update when using Control Center. If you try my dark mode demo you will see the same issue.

The only possible solution I can think of is to somehow force a redraw in the listener if the mode has changed.
